spring.application.name=employee-service-eureka
server.port=8001

spring.datasource.url=jdbc:mysql://localhost:3306/employeeservicedb?createDatabaseIfNotExist=true 
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Définissez votre chemin de contexte ici
server.servlet.context-path=/employee-service