spring.application.name=employee-service-eureka
server.port=8001
application.title=employee-service-eureka
application.version=1.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/employeeservicedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.cloud.openfeign=DEBUG

# Le serveur s'enregistre auprès de son pair
#eureka.client.register-with-eureka=true

# Le serveur récupère le registre de son pair
#eureka.client.fetch-registry=false

# si plusieurs serveur Eureka, mettre plusieurs URL
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

# Eureka sur lequel enregistrer les instances
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
