spring.application.name=employee-service-eureka

spring.datasource.url=jdbc:mysql://localhost:3306/employeeservicedb?createDatabaseIfNotExist=true 
spring.datasource.username=root
spring.datasource.password=
server.port=8080
# Définissez votre chemin de contexte ici
server.servlet.context-path=/employee-service